In [43]:
import pandas as pd
import numpy as np
import os

In [44]:
#Importing the data from a csv file
not_a_dic = pd.read_csv('GSAF5.csv',sep=',', engine='python')

In [45]:
not_a_dic.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [46]:
#Checking how much data is missing in every column in percent
not_a_dic.isna().sum()*100/len(not_a_dic)

Case Number                0.000000
Date                       0.000000
Year                       0.000000
Type                       0.000000
Country                    0.717623
Area                       6.708945
Location                   8.277704
Activity                   8.795060
Name                       3.337784
Sex                        9.462617
Age                       44.742991
Injury                     0.450601
Fatal (Y/N)                0.317089
Time                      53.621495
Species                   48.965287
Investigator or Source     0.250334
pdf                        0.000000
href formula               0.016689
href                       0.050067
Case Number.1              0.000000
Case Number.2              0.000000
original order             0.000000
Unnamed: 22               99.983311
Unnamed: 23               99.966622
dtype: float64

In [47]:
#copy for data cleaning and manipulation
not_a_dic2 = not_a_dic.copy()

In [48]:
#optimizing the column names for easier working
not_a_dic2.columns = (not_a_dic2.columns
                      .str.lower()
                      .str.strip()
                      .str.replace(' ','_')
                      .str.replace('.','_')
                     )
not_a_dic2.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal_(y/n)', 'time',
       'species', 'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number_1', 'case_number_2', 'original_order', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

In [104]:
#Checking for duplicated rows. All of them seem unique
not_a_dic2[not_a_dic2.duplicated()]

Empty DataFrame
Columns: [case_number, date, year, type, country, area, location, activity, name, sex, injury, fatal_(y/n), investigator_or_source, pdf, href_formula, href, original_order]
Index: []

In [49]:
#We are dropping every column with more than 40 percent missing data. If Age, Species or Time is importan we could subsetting a new table and work with half of the data. Decided to cut them al
drop_list = [l for l in not_a_dic2 if not_a_dic2[l].isna().sum()/len(not_a_dic2) > .4]
drop_list
not_a_dic2 = not_a_dic2.drop(drop_list, 1)

In [50]:
not_a_dic2.shape

(5992, 19)

In [51]:
#columns of Case Number, Case Number.1 and Case Number.2 are looking the same. Checking it to make sure. If yes we can drop 2 columns
not_a_dic2.query('case_number != case_number_1')

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal_(y/n),investigator_or_source,pdf,href_formula,href,case_number_1,case_number_2,original_order
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,No injury: Knocked off board by shark,N,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989
33,2016.07.14.4,Reported 14-Jul-2016,2016,Unprovoked,BAHAMAS,NaN,Tiger Beach,Scuba Diving,Michael Dornellas,M,Face bruised when partly blind shark collided ...,N,"GrindTV, 7/14/2016",2016.07.14.R-TigerBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.14.R,2016.07.14.4,5960
97,2016.01.24.b,24-Jan-16,2016,Unprovoked,USA,Texas,Off Surfside,Spearfishing,Keith Love,M,"Bruised ribs & tail bone, speargun broken and ...",N,K. Love,2016.01.24.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.24.b,2016.01.24.b,5896
116,2015.12.23,07-Nov-15,2015,Invalid,USA,Florida,"Paradise Beach, Melbourne, Brevard County",Surfing,Ryla Underwood,F,Lower left leg injured,N,"Fox25Orlando, 11/7/2015",2015.11.07-Underwood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.11.07,2015.12.23,5876
121,2015.10.28.a,28-Oct-15,2015,Unprovoked,USA,Hawaii,"Malaka, Oahu",Body boarding,Raymond Senensi,M,"Lacerations & puncture wounds to right thigh, ...",N,"Star Advertiser, 10/28/2015",2015.10.28-Senensi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.10.28,2015.10.28.a,5871
169,2015.07-10,10-Jul-15,2015,Unprovoked,USA,California,"Huntington Beach, Orange County",Surfing,Danny Miskin,M,"No injury, shark bumped & damaged board",N,"KTLA, 7/10/2015",2015.07.10-Miskin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.10,2015.07.10,5823
3296,1967.07.05,05-Jul-67,1967,Unprovoked,TURKEY,Mugla Province,Kucukada Island,Spearfishing,Gungor Guven,M,FATAL,Y,"C. Moore, GSAF",1967.07.05-Guven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1967/07.05,1967.07.05,2697
3569,"1962,08.30.b",30-Aug-62,1962,Boat,TURKEY,Antalya Province,Ucagiz,NaN,Occupant: Hasan Olta,M,No injury,N,"C.Moore, GSAF",1962.08.30.b-pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1962.08.30.b,"1962,08.30.b",2424
3654,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,Left foot & right hand bitten by netted shark ...,N,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,"1961.09,06.R",1961.09.02.R,2339
4177,1952.08.05,05-Aug-52,1952,Provoked,ITALY,Teramo,Giulianova,Fishing,Vittorio Speca,NaN,Multiple injuries PROVOKED INCIDENT,Y,"C. Moore, GSAF",1952.08.05-Speca.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.08.04,1952.08.05,1816
4719,1934.01.08.R,Reported 08-Feb-1934,1934,Boating,TURKEY,Istanbul,"Haydarpasa jetty, Istanbul",Fishing,2 males,M,No injury,N,"C. Moore, GSAF",1924.02.08.R-Turkey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1934.02.08.R,1934.02.08.R,1274
5043,1900.00.00.R,Reported to have taken place in 1919,1919,Boating,ITALY,NaN,Savona,Fishing,NaN,M,No injury,N,"C. Moore, GSAF",1919.00.00.R-Savona.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1919.00.00.R,1900.00.00.R,950
5150,1911.07.31.R,Reported 31-Jul-1911,1911,Unprovoked,SPAIN,MÃ¡laga,Ceuta,Bathing,a soldier,M,FATAL,Y,C. Moore,1911.07.31.R-Ceuta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1911.07.31.T,1911.07.31.R,843

In [52]:
not_a_dic2.query('case_number != case_number_2')

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal_(y/n),investigator_or_source,pdf,href_formula,href,case_number_1,case_number_2,original_order
169,2015.07-10,10-Jul-15,2015,Unprovoked,USA,California,"Huntington Beach, Orange County",Surfing,Danny Miskin,M,"No injury, shark bumped & damaged board",N,"KTLA, 7/10/2015",2015.07.10-Miskin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.10,2015.07.10,5823
4719,1934.01.08.R,Reported 08-Feb-1934,1934,Boating,TURKEY,Istanbul,"Haydarpasa jetty, Istanbul",Fishing,2 males,M,No injury,N,"C. Moore, GSAF",1924.02.08.R-Turkey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1934.02.08.R,1934.02.08.R,1274

In [53]:
#combining the query 
not_a_dic2.query('case_number != case_number_1 & case_number != case_number_2')

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal_(y/n),investigator_or_source,pdf,href_formula,href,case_number_1,case_number_2,original_order
169,2015.07-10,10-Jul-15,2015,Unprovoked,USA,California,"Huntington Beach, Orange County",Surfing,Danny Miskin,M,"No injury, shark bumped & damaged board",N,"KTLA, 7/10/2015",2015.07.10-Miskin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.10,2015.07.10,5823
4719,1934.01.08.R,Reported 08-Feb-1934,1934,Boating,TURKEY,Istanbul,"Haydarpasa jetty, Istanbul",Fishing,2 males,M,No injury,N,"C. Moore, GSAF",1924.02.08.R-Turkey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1934.02.08.R,1934.02.08.R,1274

In [54]:
#only 2 columns are different and those looking like typos. We can drop case_number_1 and case_number_2
not_a_dic2 = not_a_dic2.drop(['case_number_1', 'case_number_2'], 1)

In [ ]:
#Taking care of columns pdf, href and href_formula. They are all handling the reference
#pdf has no missing data, href_formula 1 and href 3

In [119]:
not_a_dic2.loc[not_a_dic2['href_formula'].isna()]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal_(y/n),investigator_or_source,pdf,href_formula,href,original_order
3019,1975.01.19,19-Jan-75,1975,Unprovoked,AUSTRALIA,South Australia,Coffin Bay,Surfing,David Barrowman,M,"FATAL, body not recovered",Y,"J. West; Adelaide Advertiser, 1/20/1975; P. Ke...",1975.01.19-Barrowman.pdf,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,2974

In [120]:
len(not_a_dic2.query('href_formula != href'))
#Difference is under 1 percent.

54

In [122]:
#We can use the href value to fill our href_value. With more than 1 row we would need to use a for loop.

not_a_dic2.loc[pd.isna(not_a_dic2['href_formula']), 'href_formula'] = not_a_dic2.loc[pd.isna(not_a_dic2['href_formula']),'href']

In [125]:
not_a_dic2['href_formula'].isna().sum()

0

In [126]:
#Now we can drop pdf and href column

not_a_dic2 = not_a_dic2.drop(['pdf','href'],1)

In [131]:
not_a_dic2.isna().sum()*100/len(not_a_dic2)

case_number               0.000000
date                      0.000000
year                      0.000000
type                      0.000000
country                   0.717623
area                      6.708945
location                  8.277704
activity                  8.795060
name                      3.337784
sex                       9.462617
injury                    0.450601
fatal_(y/n)               0.317089
investigator_or_source    0.250334
href_formula              0.000000
original_order            0.000000
dtype: float64

In [207]:
#We getting rid of some unreliable data by reducing the time frame

columns_keep = not_a_dic2.columns

not_a_dic3 = not_a_dic2[(not_a_dic2['year']>=1800)][columns_keep]

In [208]:
#We also getting rid of the original order because we using a new index later. The date column is also too unspecific in it's values

not_a_dic3 = not_a_dic3.drop(['date','original_order'], 1)

In [209]:
#cleaning up the fatal column
not_a_dic3['fatal_(y/n)'] = (not_a_dic3['fatal_(y/n)']
                             .str.strip()
                             .str.upper()
                             .str.replace('F', 'ND')
                             .str.replace('UNKNOWN','ND')
                             .str.replace('#VALUE!', 'ND')
                             .fillna('ND')
                    )

In [210]:
#cleaning sex column
not_a_dic3['sex'] = (not_a_dic3['sex']
                             .str.strip()
                             .str.upper()
                             .str.replace('LLI', 'M')
                             .str.replace('N','ND')
                             .str.replace('.', 'ND')
                             .fillna('ND')
                    )

In [211]:
#cleaning up the country column by dropping the NAN rows
not_a_dic3['country'].isna().sum()

35

In [212]:
not_a_dic3.dropna(subset=['country'],inplace=True)

In [213]:
#drop the name column because the information shouldn't be relevant unless for insurance reasons, but then it is filled with too much bad data
not_a_dic3 = not_a_dic3.drop('name',1)

In [217]:
#filling the NAN in the other columns with ND (No Data)
not_a_dic3.fillna('ND', inplace=True)

In [218]:
not_a_dic3.isna().sum()*100/len(not_a_dic3)

case_number               0.0
year                      0.0
type                      0.0
country                   0.0
area                      0.0
location                  0.0
activity                  0.0
sex                       0.0
injury                    0.0
fatal_(y/n)               0.0
investigator_or_source    0.0
href_formula              0.0
dtype: float64

In [229]:
#Renaming for better understanding
not_a_dic3.rename(columns ={'fatal_(y/n)': 'death',
                            'investigator_or_source': 'source',
                            'href_formula': 'reference',
                            'type' : 'type of accident',
                            'case_number' : 'case number'},
                  inplace=True)

In [230]:
#Reseting the index
not_a_dic3.reset_index(drop=True, inplace=True)

In [231]:
#writing into a pickle file
not_a_dic3.to_pickle('new_shark_in_town.pkl')